CREATE DATABASE power CHARACTER SET utf8mb4    COLLATE utf8mb4_unicode_ci;
use power;
CREATE TABLE `company` (
  `id` bigint not null AUTO_INCREMENT,
  `项目名称` varchar(20) COLLATE utf8mb4_unicode_ci,
  `容量` text COLLATE utf8mb4_unicode_ci,
  `日均风速` text COLLATE utf8mb4_unicode_ci,
  `日发电量` text COLLATE utf8mb4_unicode_ci,
  `日限电量` text COLLATE utf8mb4_unicode_ci,
  `上报日限电比例` text COLLATE utf8mb4_unicode_ci,
  `月发电量` text COLLATE utf8mb4_unicode_ci,
  `月限电量` text COLLATE utf8mb4_unicode_ci,
  `月利用小时` text COLLATE utf8mb4_unicode_ci,
  `上报月度限电比例` text COLLATE utf8mb4_unicode_ci,
  `月计划电量` text COLLATE utf8mb4_unicode_ci,
  `月计划完成率` text COLLATE utf8mb4_unicode_ci,
  `年发电量` text COLLATE utf8mb4_unicode_ci,
  `年限电量` text COLLATE utf8mb4_unicode_ci,
  `年利用小时` text COLLATE utf8mb4_unicode_ci,
  `上报年度限电比例` text COLLATE utf8mb4_unicode_ci,
  `年计划电量` text COLLATE utf8mb4_unicode_ci,
  `年计划完成率` text COLLATE utf8mb4_unicode_ci,
  `组` bigint DEFAULT NULL,
  `时间` varchar(20) COLLATE utf8mb4_unicode_ci,
  `_fold` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_name_time` (`项目名称`, `时间`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `wind` (
  `id` bigint not null AUTO_INCREMENT,
  `项目名称` varchar(20) COLLATE utf8mb4_unicode_ci,
  `容量` text COLLATE utf8mb4_unicode_ci,
  `日发电量` text COLLATE utf8mb4_unicode_ci,
  `日限电量` text COLLATE utf8mb4_unicode_ci,
  `上报日限电比例` text COLLATE utf8mb4_unicode_ci,
  `日综合场用电率` text COLLATE utf8mb4_unicode_ci,
  `月发电量` text COLLATE utf8mb4_unicode_ci,
  `月限电量` text COLLATE utf8mb4_unicode_ci,
  `月利用小时` text COLLATE utf8mb4_unicode_ci,
  `上报月度限电比例` text COLLATE utf8mb4_unicode_ci,
  `月计划电量` text COLLATE utf8mb4_unicode_ci,
  `月计划完成率` text COLLATE utf8mb4_unicode_ci,
  `年发电量` text COLLATE utf8mb4_unicode_ci,
  `年限电量` text COLLATE utf8mb4_unicode_ci,
  `年利用小时` text COLLATE utf8mb4_unicode_ci,
  `上报年度限电比例` text COLLATE utf8mb4_unicode_ci,
  `年计划电量` text COLLATE utf8mb4_unicode_ci,
  `年计划完成率` text COLLATE utf8mb4_unicode_ci,
  `日上网电量` text COLLATE utf8mb4_unicode_ci,
  `日购网电量` text COLLATE utf8mb4_unicode_ci,
  `月上网电量` text COLLATE utf8mb4_unicode_ci,
  `月购网电量` text COLLATE utf8mb4_unicode_ci,
  `年上网电量` text COLLATE utf8mb4_unicode_ci,
  `年购网电量` text COLLATE utf8mb4_unicode_ci,
  `组` bigint DEFAULT NULL,
  `时间` varchar(20) COLLATE utf8mb4_unicode_ci,
  `_fold` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_name_time` (`项目名称`, `时间`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `project` (
  `id` bigint not null AUTO_INCREMENT,
  `项目名称` varchar(20) COLLATE utf8mb4_unicode_ci,
  `容 量` text COLLATE utf8mb4_unicode_ci,
  `日均风速` text COLLATE utf8mb4_unicode_ci,
  `日发电量` text COLLATE utf8mb4_unicode_ci,
  `日限电量` text COLLATE utf8mb4_unicode_ci,
  `上报日限电比例` text COLLATE utf8mb4_unicode_ci,
  `月发电量` text COLLATE utf8mb4_unicode_ci,
  `月限电量` text COLLATE utf8mb4_unicode_ci,
  `月利用小时` text COLLATE utf8mb4_unicode_ci,
  `上报月度限电比例` text COLLATE utf8mb4_unicode_ci,
  `月计划电量` text COLLATE utf8mb4_unicode_ci,
  `月计划完成率` text COLLATE utf8mb4_unicode_ci,
  `年发电量` text COLLATE utf8mb4_unicode_ci,
  `年限电量` text COLLATE utf8mb4_unicode_ci,
  `年利用小时` text COLLATE utf8mb4_unicode_ci,
  `上报年度限电比例` text COLLATE utf8mb4_unicode_ci,
  `年计划电量` text COLLATE utf8mb4_unicode_ci,
  `年计划完成率` text COLLATE utf8mb4_unicode_ci,
  `日上网电量` text COLLATE utf8mb4_unicode_ci,
  `日购网电量` text COLLATE utf8mb4_unicode_ci,
  `月上网电量` text COLLATE utf8mb4_unicode_ci,
  `月购网电量` text COLLATE utf8mb4_unicode_ci,
  `年上网电量` text COLLATE utf8mb4_unicode_ci,
  `年购网电量` text COLLATE utf8mb4_unicode_ci,
  `组` bigint DEFAULT NULL,
  `时间` varchar(20) COLLATE utf8mb4_unicode_ci,
  `_fold` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_name_time` (`项目名称`, `时间`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;