CREATE TABLE `company_power` (
  `id` bigint not null AUTO_INCREMENT,
  `组` bigint DEFAULT NULL,
  `项目名称` text COLLATE utf8mb4_unicode_ci,
  `容量` text COLLATE utf8mb4_unicode_ci,
  `日均风速` text COLLATE utf8mb4_unicode_ci,
  `日发电量` text COLLATE utf8mb4_unicode_ci,
  `日限电量` text COLLATE utf8mb4_unicode_ci,
  `上报日限电比例` text COLLATE utf8mb4_unicode_ci,
  `月发电量` text COLLATE utf8mb4_unicode_ci,
  `月限电量` text COLLATE utf8mb4_unicode_ci,
  `月利用小时` text COLLATE utf8mb4_unicode_ci,
  `上报月度限电比例` text COLLATE utf8mb4_unicode_ci,
  `月计划电量` text COLLATE utf8mb4_unicode_ci,
  `月计划完成率` text COLLATE utf8mb4_unicode_ci,
  `年发电量` text COLLATE utf8mb4_unicode_ci,
  `年限电量` text COLLATE utf8mb4_unicode_ci,
  `年利用小时` text COLLATE utf8mb4_unicode_ci,
  `上报年度限电比例` text COLLATE utf8mb4_unicode_ci,
  `年计划电量` text COLLATE utf8mb4_unicode_ci,
  `年计划完成率` text COLLATE utf8mb4_unicode_ci,
  `时间` text COLLATE utf8mb4_unicode_ci,
  `_fold` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
